services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
      - ./data/logs:/app/logs
      - ./books:/app/books
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-jwt-secret-key-change-in-production}
      - DATABASE=/app/data/shadowrealms.db
      - CHROMADB_HOST=localhost
      - CHROMADB_PORT=8000
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - GPU_THRESHOLD_HIGH=80
      - GPU_THRESHOLD_MEDIUM=60
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/backend.log
      # LLM Service Configuration
      - LM_STUDIO_URL=http://localhost:1234
      - LM_STUDIO_API_KEY=${LM_STUDIO_API_KEY:-}
      - LM_STUDIO_MODEL=${LM_STUDIO_MODEL:-mythomakise-merged-13b}
      - LM_STUDIO_TIMEOUT=${LM_STUDIO_TIMEOUT:-30}
      - OLLAMA_URL=http://localhost:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-command-r:35b}
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-30}
    depends_on:
      - chromadb
      - monitoring
    network_mode: "host"
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/vector_db:/data
    networks:
      - shadowrealms-network
    restart: unless-stopped

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./data/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - shadowrealms-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - shadowrealms-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shadowrealms-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    network_mode: "host"
    restart: unless-stopped

volumes:
  redis_data:

networks:
  shadowrealms-network:
    driver: bridge
